ethereum_rpc = "https://0xrpc.io/hoodi"
drosera_rpc = "https://relay.hoodi.drosera.io"
eth_chain_id = 560048
drosera_address = "0x91cB447BaFc6e0EA0F4Fe056F5a9b1F14bb06e5D"

[traps.silent_drain]

path = "out/SilentDrainTrap.sol/SilentDrainTrap.json"

response_contract = "0x1f5d77a8043E874BE3FCF0067D0d44979aa0831E"
response_function = "respondToSilentDrain(address,uint256,uint256,uint256,uint256)"

cooldown_period_blocks = 30
min_number_of_operators = 1
max_number_of_operators = 2

# Windowed detection
block_sample_size = 6

private_trap = true

# MUST be operator EOAs, not SAFE or contracts
whitelist = [""]
